# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Myproject\Python\IdVerification\FormUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(429, 191)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.getfilebutton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.getfilebutton.sizePolicy().hasHeightForWidth())
        self.getfilebutton.setSizePolicy(sizePolicy)
        self.getfilebutton.setObjectName("getfilebutton")
        self.horizontalLayout.addWidget(self.getfilebutton)
        self.filelabel = QtWidgets.QLabel(self.centralwidget)
        self.filelabel.setText("")
        self.filelabel.setObjectName("filelabel")
        self.horizontalLayout.addWidget(self.filelabel)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.sheetlist = QtWidgets.QListWidget(self.centralwidget)
        self.sheetlist.setObjectName("sheetlist")
        self.horizontalLayout_3.addWidget(self.sheetlist)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.idbutton = QtWidgets.QRadioButton(self.centralwidget)
        self.idbutton.setObjectName("idbutton")
        self.horizontalLayout_2.addWidget(self.idbutton)
        self.numbutton = QtWidgets.QRadioButton(self.centralwidget)
        self.numbutton.setObjectName("numbutton")
        self.horizontalLayout_2.addWidget(self.numbutton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.rangecombom = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rangecombom.sizePolicy().hasHeightForWidth())
        self.rangecombom.setSizePolicy(sizePolicy)
        self.rangecombom.setObjectName("rangecombom")
        self.verticalLayout.addWidget(self.rangecombom)
        self.runbutton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runbutton.sizePolicy().hasHeightForWidth())
        self.runbutton.setSizePolicy(sizePolicy)
        self.runbutton.setObjectName("runbutton")
        self.verticalLayout.addWidget(self.runbutton)
        self.exitbutton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exitbutton.sizePolicy().hasHeightForWidth())
        self.exitbutton.setSizePolicy(sizePolicy)
        self.exitbutton.setObjectName("exitbutton")
        self.verticalLayout.addWidget(self.exitbutton)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "适用于验证身份证和联系方式的程序  --by@8bit"))
        self.getfilebutton.setText(_translate("MainWindow", "选择文件"))
        self.idbutton.setText(_translate("MainWindow", "身份证号"))
        self.numbutton.setText(_translate("MainWindow", "联系方式"))
        self.runbutton.setText(_translate("MainWindow", "开始执行"))
        self.exitbutton.setText(_translate("MainWindow", "结束程序"))
